### ISSUE TITLE
需要适配 PhpStorm 2024.2

### ISSUE THREAD

**Issue by liangchenwsl** [kkguan/php-accessor#4]
php-accessor的ide插件目前不支持PhpStorm 2024.2，需要适配一下

**Comment by free2one** [comment]
新版本已经支持了，等插件市场那边审核通过就能更新。
另外，插件相关的问题可以提到[php-accessor-idea-plugin的仓库](https://github.com/kkguan/php-accessor-idea-plugin)。

**Comment by free2one** [comment]
![d8065931-ef72-4e6d-ae74-30c8b5cd0202](https://github.com/user-attachments/assets/4374e871-a174-4238-8f12-0860f36452fb)

**Comment by twose** [comment]
Closes kkguan/php-accessor-idea-plugin@0019d45.
